name: foodbalance
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^20.0.0
  google_generative_ai: ^0.4.7
  google_sign_in: ^6.2.1
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  lottie: ^3.3.2
  mobile_scanner: ^7.1.4
  path: ^1.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  timezone: ^0.10.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#FDF7C3"
  image: assets/logo/FB_logo.png

  android: true
  ios: true

  android_12:
    image: assets/logo/small_logo.png
    color: "#FDF7C3"
    icon_background_color: "#FDF7C3"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/lottie/
    - .env
